### PR TITLE
Updated and revised README.md, together with an example screenshot.

### PR DESCRIPTION
**Pull request by flipbit03**
Saw this on Hacker News and thought together with some other peers at the discussion that it would be better for this project to have a screenshot inside the README.md. 

I also revised some wordings here and there.

### CODE REVIEW

**Comment by flipbit03** [comment]
Yes! I'm going to try to work on this when I have some downtime o/

**Comment by flipbit03** [comment]
I'm gonna rerun the software and update the **screenshot** as well

**Comment by gsquire** [comment]
Sounds like a plan. Feel free to ping me with any questions you may have.

**Comment by gsquire** [comment]
Hey @flipbit03! I ended up cherry picking some of your commit and merged it into the README. I added a new screenshot too. I also implemented the first cut of log tailing so if that interests you, I hope it works well!

Thanks again for your patch and I hope you can contribute again in the future!

**Pull request closed without merging**
